# covers https://github.com/craftcms/rector/issues/5
name: Install in Craft CMS

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    install_in_craftcms:
        runs-on: ubuntu-latest

        steps:
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   run: git clone https://github.com/craftcms/cms.git --depth 1 --ansi
            -   run: cd cms && composer require craftcms/rector:dev-main --dev --ansi
